// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WhatzMeApiApp.Requests;
//
//    var enviarArchivoPeticion = EnviarArchivoPeticion.FromJson(jsonString);

namespace WhatzMeApiApp.Requests
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EnviarArchivoPeticion
    {
        [JsonProperty("numero")]
        public string Numero { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("nombrearchivo")]
        public string Nombrearchivo { get; set; }

        [JsonProperty("textoimagen")]
        public string Textoimagen { get; set; }
    }

    public partial class EnviarArchivoPeticion
    {
        public static EnviarArchivoPeticion FromJson(string json) => JsonConvert.DeserializeObject<EnviarArchivoPeticion>(json, WhatzMeApiApp.Requests.ConverterEnviarArchivo.Settings);
    }

    public static class SerializeEnviarArchivo
    {
        public static string ToJson(this EnviarArchivoPeticion self) => JsonConvert.SerializeObject(self, WhatzMeApiApp.Requests.ConverterEnviarArchivo.Settings);
    }

    internal static class ConverterEnviarArchivo
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
