// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WhatzMeApiApp.Requests;
//
//    var enviarMensajePeticion = EnviarMensajePeticion.FromJson(jsonString);

namespace WhatzMeApiApp.Requests
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EnviarMensajePeticion
    {
        [JsonProperty("numero")]
        public string Numero { get; set; }

        [JsonProperty("mensaje")]
        public string Mensaje { get; set; }
    }

    public partial class EnviarMensajePeticion
    {
        public static EnviarMensajePeticion FromJson(string json) => JsonConvert.DeserializeObject<EnviarMensajePeticion>(json, WhatzMeApiApp.Requests.ConverterEnviarMensaje.Settings);
    }

    public static class SerializeEnviarMensaje
    {
        public static string ToJson(this EnviarMensajePeticion self) => JsonConvert.SerializeObject(self, WhatzMeApiApp.Requests.ConverterEnviarMensaje.Settings);
    }

    internal static class ConverterEnviarMensaje
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
