// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WhatzMeApiApp.Requests;
//
//    var enviarUbicacionPeticion = EnviarUbicacionPeticion.FromJson(jsonString);

namespace WhatzMeApiApp.Requests
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EnviarUbicacionPeticion
    {
        [JsonProperty("numero")]
        public string Numero { get; set; }

        [JsonProperty("latitud")]
        public double Latitud { get; set; }

        [JsonProperty("longitud")]
        public double Longitud { get; set; }

        [JsonProperty("direccion")]
        public string Direccion { get; set; }
    }

    public partial class EnviarUbicacionPeticion
    {
        public static EnviarUbicacionPeticion FromJson(string json) => JsonConvert.DeserializeObject<EnviarUbicacionPeticion>(json, WhatzMeApiApp.Requests.ConverterEnviarUbicacion.Settings);
    }

    public static class SerializeEnviarUbicacion
    {
        public static string ToJson(this EnviarUbicacionPeticion self) => JsonConvert.SerializeObject(self, WhatzMeApiApp.Requests.ConverterEnviarUbicacion.Settings);
    }

    internal static class ConverterEnviarUbicacion
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
