// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WhatzMeApiApp.Requests;
//
//    var enviarVariosMensajesPeticion = EnviarVariosMensajesPeticion.FromJson(jsonString);

namespace WhatzMeApiApp.Requests
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EnviarVariosMensajesPeticion
    {
        [JsonProperty("numeros")]
        public List<string> Numeros { get; set; }

        [JsonProperty("mensaje")]
        public string Mensaje { get; set; }
    }

    public partial class EnviarVariosMensajesPeticion
    {
        public static EnviarVariosMensajesPeticion FromJson(string json) => JsonConvert.DeserializeObject<EnviarVariosMensajesPeticion>(json, WhatzMeApiApp.Requests.ConverterEnviarVariosMensajes.Settings);
    }

    public static class SerializeEnviarVariosMensajes
    {
        public static string ToJson(this EnviarVariosMensajesPeticion self) => JsonConvert.SerializeObject(self, WhatzMeApiApp.Requests.ConverterEnviarVariosMensajes.Settings);
    }

    internal static class ConverterEnviarVariosMensajes
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
