// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WhatzMeApiApp.Requests;
//
//    var enviarVariosArchivosPeticion = EnviarVariosArchivosPeticion.FromJson(jsonString);

namespace WhatzMeApiApp.Requests
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EnviarVariosArchivosPeticion
    {
        [JsonProperty("numeros")]
        public List<string> Numeros { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("nombrearchivo")]
        public string Nombrearchivo { get; set; }

        [JsonProperty("textoimagen")]
        public string Textoimagen { get; set; }
    }

    public partial class EnviarVariosArchivosPeticion
    {
        public static EnviarVariosArchivosPeticion FromJson(string json) => JsonConvert.DeserializeObject<EnviarVariosArchivosPeticion>(json, WhatzMeApiApp.Requests.ConverterEnviarVariosArchivos.Settings);
    }

    public static class SerializeEnviarVariosArchivos
    {
        public static string ToJson(this EnviarVariosArchivosPeticion self) => JsonConvert.SerializeObject(self, WhatzMeApiApp.Requests.ConverterEnviarVariosArchivos.Settings);
    }

    internal static class ConverterEnviarVariosArchivos
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
